name: CI
#Created based on https://www.youtube.com/watch?v=vBEcTN5lwJc&ab_channel=CameronMcKenzie

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PostgreSQL
        # uses: Harmon758/postgresql-action@0be19fa37850b22cb4c9bbf28a03abbf44abd863
        uses: Harmon758/postgresql-action@v1.0.0
        with:
          postgresql version: latest
          postgresql db: postgres 
          postgresql user: postgres
          postgresql password: postgres
          
      - name: Checkout main branch from GitHub
        uses: actions/checkout@v2
      
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 17
          
      - name: Compile code with Maven
        run: mvn compile
        
      - name: Run Maven clean install
        run: mvn clean install
          
      - name: Build Maven Project
        run: mvn -B package --file pom.xml
        
  
      
