name: CI
#Created based on https://www.youtube.com/watch?v=vBEcTN5lwJc&ab_channel=CameronMcKenzie

on:
  push:
    branches: [ main ]
    
jobs:
  postgresDB:
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container: node:10.18-jessie
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    steps:
      - name: Checkout main branch from GitHub
        uses: actions/checkout@v2
          
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/<whatever>
      options: --user root
    steps:
      - name: Checkout main branch from GitHub
        uses: actions/checkout@v2
      
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 17
          
      - name: Compile code with Maven
        run: mvn compile
        
      - name: Run Maven clean install
        run: mvn clean install -Dactive.profile=dev
          
      - name: Build Maven Project
        run: mvn -B package --file pom.xml
        
  
      
