name: CI
#Created based on https://www.youtube.com/watch?v=vBEcTN5lwJc&ab_channel=CameronMcKenzie

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout main branch from GitHub
        uses: actions/checkout@v2
      
      - name: Set up JDK 1.8
        uses: actions/setup-java@1
        with:
          java-version: 1.8
          
      - name: Build Maven Project
        run: mvn -B package --file pom.xml
      
